name: Build, Push and Deploy Docker image to EC2
on:
  push:
    branches:
      - main
      - punidha

jobs:
  build_and_deploy:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build ./client/ -t punidha/front:v1.0

      # Step 3: Log in to Docker Hub and push the image
      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.EC2token }}
        
      - name: Push Docker image to Docker Hub
        run: |
          docker push punidha/front:v1.0

      # Step 4: SSH into EC2 instance and pull the image from Docker Hub
      - name: SSH into EC2 and deploy Docker image
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            # Pull the image from Docker Hub
            docker pull punidha/front:v1.0
 
            # Stop and remove any existing container (optional)
            docker rm -f front-container || true

            # Run the Docker container
            docker run -d --name front-container -p 80:80 punidha/front:v1.0
          EOF
