name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (client and server)
        run: |
          cd client && npm ci
          cd ../server && npm ci

      - name: Run tests and collect coverage (client and server)
        run: |
          cd client && npm run test -- --coverage --watchAll=false --passWithNoTests
          cd ../server && npm run test -- --coverage --watchAll=false --passWithNoTests

           - name: Combine lcov reports
        shell: bash
        run: |
          mkdir -p coverage
          # Only copy lcov report if it exists
          if [ -f client/coverage/lcov.info ]; then cp client/coverage/lcov.info coverage/lcov-client.info; fi
          if [ -f server/coverage/lcov.info ]; then cp server/coverage/lcov.info coverage/lcov-server.info; fi
          # Combine lcov info if both reports exist
          if [ -f coverage/lcov-client.info ] && [ -f coverage/lcov-server.info ]; then
            cat coverage/lcov-*.info > coverage/lcov.info
          elif [ -f coverage/lcov-client.info ]; then
            cp coverage/lcov-client.info coverage/lcov.info
          elif [ -f coverage/lcov-server.info ]; then
            cp coverage/lcov-server.info coverage/lcov.info
          fi


      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
